# Generated by Django 6.0.4 on 2026-04-24 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_area_division_route_outlet_zone_area_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='area',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='division',
        ),
        migrations.RemoveField(
            model_name='outlet',
            name='route',
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='Division',
        ),
        migrations.DeleteModel(
            name='Zone',
        ),
        migrations.DeleteModel(
            name='Outlet',
        ),
        migrations.DeleteModel(
            name='Route',
        ),
    ]
